version: "3.9"
services:
  my-sql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    volumes:
      - ./data/mysql:/var/lib/mysql